name: docs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  docs:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry==1.4.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: "poetry"

      - name: Install Poetry dependencies
        run: poetry install

      - name: Check package
        run: pip show malariagen_data

      - name: Install Sphinx dependencies
        run: |
          pip install -r ./docs/requirements.txt

      - name: Build HTML
        run: |
          cd docs/
          sphinx-build -b html -a -E -j auto -n source build --keep-going

      - name: Deploy HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html