name: docs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  documentation:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r ./docs/requirements.txt

      - name: Build
        run: |
          cd docs/
          sphinx-build -b html source build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html